console.log ('Ex 13:');
console.log ('let n = prompt ( ' + `${'Enter n:'}` + ' ); ' );
console.log ('{');
console.log ('for (var m=1; m<=n; m++)');
console.log ('for (var i=1; i <= n; i++)');
console.log ('{');
console.log ('fd(50)');
console.log ('lt(360/n)');
console.log ('}');
console.log ('}');